# Generated by Django 4.0 on 2022-04-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
