# Generated by Django 4.0 on 2022-04-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_bid_listing_remove_comment_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=300)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.URLField(default=' ')),
                ('sold', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_by_user', to='auctions.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
